dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.home, name="home"),
    path('load_work_items/', views.load_work_items, name="load_work_items"),
    path('create_webhook/', views.create_webhook, name="create_webhook"),
    path('workitem/<str:pk>/', views.workitem, name="workitem"),

    path('create_comment/<str:pk>/', views.create_comment, name="create_comment"),
    path('update_comment/<str:pk>/', views.update_comment, name="update_comment"),
    path('delete_comment/<str:pk>/', views.delete_comment, name="delete_comment"),

    path('update_in_DM/<str:pk>/', views.update_in_DM, name="update_in_DM"),
    path('update_hours/<str:pk>/', views.update_hours, name="update_hours"),
    path('update_ad_work_package/<str:pk>/', views.update_ad_work_package, name="update_ad_work_package"),

    path('create_IA/<str:pk>/', views.create_IA, name="create_IA"),
    path('create_CR/<str:pk>/', views.create_CR, name="create_CR"),
    path('bulkcreate_IA/', views.bulkcreate_IA, name="bulkcreate_IA"),
    path('reset_IA/', views.reset_IA, name="reset_IA"),

    path('download/IA/', views.download_ia, name="download_ia"),
    path('download/CR/', views.download_cr, name="download_cr"),
    path('download_ia/<str:filename>/', views.download_doc, name="download_doc"),
    path('download_cr/<str:filename>/', views.download_excel, name="download_excel")

]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls'))
]

dashboard/models.py
from datetime import datetime
from django.db import models


# Create your models here.


class WorkItem(models.Model):
    id = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=200, null=False)
    state = models.CharField(max_length=200, null=False)
    has_IA = models.BooleanField(default=False)
    has_CR = models.BooleanField(default=False)
    created = models.DateTimeField(default=datetime.now())
    description = models.TextField(default='')
    owner = models.CharField(max_length=200, null=False, default='')
    in_DM = models.BooleanField(default=0)
    hours = models.IntegerField(default=0)
    ad_work_package = models.CharField(max_length=50, null=False, default='')
    '''owners end date'''


class Comment(models.Model):
    work_item = models.ForeignKey(WorkItem, on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.body[0:15]

dashboard/forms.py
from django import forms

dashboard/views.py
from glob import glob
import mimetypes
import os
from xml.etree.ElementTree import Comment
from django.shortcuts import redirect, render
from django.shortcuts import render
from dashboard.doc_utils import create_doc
from dashboard.excel_utils import create_excel

from dashboard.models import WorkItem, Comment
from .utils import get_work_items, Details
from django.http import HttpResponse, HttpResponseRedirect
from dateutil import parser
from django.urls import reverse
from django.views.decorators.csrf import csrf_protect, csrf_exempt

from zipfile import ZipFile

# Create your views here.


def home(request):
    work_items_list = WorkItem.objects.all()
    context = {
        'work_items_list': work_items_list
    }
    return render(request, 'dashboard/index.html', context)

@csrf_exempt
def create_webhook(request):
    work_items = get_work_items(
        Details.PERSONAL_ACCESS_TOKEN,
        Details.ORGANIZATION_URL,
        Details.QUERY_ID
    )

    for work_item_id, work_item in work_items.items():
        try:
            work_item_object = WorkItem.objects.get(id=work_item_id)
            if work_item_object.title != work_item.fields['System.Title']:
                work_item_object.title = work_item.fields['System.Title']
                work_item_object.save()
            if work_item_object.state != work_item.fields['System.State']:
                work_item_object.state = work_item.fields['System.State']
                work_item_object.save()
            if work_item_object.description != work_item.fields['System.Description']:
                work_item_object.description = work_item.fields['System.Description']
                work_item_object.save()

        except WorkItem.DoesNotExist:
            datetime_string = work_item.fields['System.CreatedDate']
            datetime_object = parser.isoparse(datetime_string)
            work_item_object = WorkItem.objects.get_or_create(
                id=work_item_id,
                title=work_item.fields['System.Title'],
                state=work_item.fields['System.State'],
                created=datetime_object,
                description=work_item.fields['System.Description'],
                owner=work_item.fields['System.CreatedBy']['displayName']
            )

    return home(request)    


def load_work_items(request):
    work_items = get_work_items(
        Details.PERSONAL_ACCESS_TOKEN,
        Details.ORGANIZATION_URL,
        Details.QUERY_ID
    )

    for work_item_id, work_item in work_items.items():
        try:
            work_item_object = WorkItem.objects.get(id=work_item_id)
            if work_item_object.title != work_item.fields['System.Title']:
                work_item_object.title = work_item.fields['System.Title']
                work_item_object.save()
            if work_item_object.state != work_item.fields['System.State']:
                work_item_object.state = work_item.fields['System.State']
                work_item_object.save()
            if work_item_object.description != work_item.fields['System.Description']:
                work_item_object.description = work_item.fields['System.Description']
                work_item_object.save()

        except WorkItem.DoesNotExist:
            datetime_string = work_item.fields['System.CreatedDate']
            datetime_object = parser.isoparse(datetime_string)
            work_item_object = WorkItem.objects.get_or_create(
                id=work_item_id,
                title=work_item.fields['System.Title'],
                state=work_item.fields['System.State'],
                created=datetime_object,
                description=work_item.fields['System.Description'],
                owner=work_item.fields['System.CreatedBy']['displayName']
            )

    return home(request)


def workitem(request, pk):
    work_item = WorkItem.objects.get(id=pk)
    work_item_comments = work_item.comment_set.all()
    context = {
        'work_item': work_item,
        'work_item_comments': work_item_comments
    }
    return render(request, 'dashboard/workitem.html', context)


@csrf_exempt
def create_comment(request, pk):
    work_item = WorkItem.objects.get(id=pk)
    if request.method == 'POST':
        comment = Comment.objects.create(
            work_item=work_item,
            body=request.POST.get('body')
        )

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@csrf_exempt
def update_comment(request, pk):
    comment_query = Comment.objects.filter(id=pk)
    comment = comment_query.first()
    if request.method == 'POST':
        comment.body = request.POST.get('body')
        comment.save()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@csrf_exempt
def delete_comment(request, pk):
    comment_query = Comment.objects.filter(id=pk)
    comment = comment_query.first()
    work_item = comment.work_item
    comment_query.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def update_in_DM(request, pk):
    work_item = WorkItem.objects.get(id=pk)
    if request.method == 'POST':
        comment = Comment.objects.create(
            work_item=work_item,
            body=request.POST.get('body')
        )

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def update_hours(request, pk):
    work_item = WorkItem.objects.get(id=pk)
    if request.method == 'POST':
        work_item.hours = int(request.POST.get('hours'))
        work_item.save()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def update_ad_work_package(request, pk):
    work_item = WorkItem.objects.get(id=pk)
    if request.method == 'POST':
        comment = Comment.objects.create(
            work_item=work_item,
            body=request.POST.get('body')
        )

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def create_IA(request, pk):
    work_item = WorkItem.objects.get(id=pk)
    doc_details = create_doc(work_item)

    if doc_details['file_path'] is not None:
        work_item.has_IA = True
        work_item.save()

        filename = doc_details['file_name']
        filepath = doc_details['file_path']
        if os.path.exists(filepath):
            # !!Important read as binary!!
            with open(filepath, 'rb') as worddoc:
                content = worddoc.read()
                response = HttpResponse(
                    content,
                    content_type='application/vnd.openxmlformats-officedocument.wordprocessingml.document'
                )
                response['Content-Disposition'] = f'attachment; filename={filename}'
                response['Content-Length'] = len(content)
                return response
        else:
            work_item_comments = work_item.comment_set.all()
            context = {
                'work_item': work_item,
                'work_item_comments': work_item_comments,
                'message_ia': doc_details['message']
            }
            return render(request, 'dashboard/workitem.html', context)

    else:
        work_item_comments = work_item.comment_set.all()
        context = {
            'work_item': work_item,
            'work_item_comments': work_item_comments,
            'message_ia': doc_details['message']
        }
        return render(request, 'dashboard/workitem.html', context)


def bulkcreate_IA(request):
    work_items = WorkItem.objects.filter(has_IA=False)
    created_IA_docs = []
    for work_item in work_items:
        doc_details = create_doc(work_item)
        if doc_details['file_path']:
            created_IA_docs.append(doc_details['file_path'])
            work_item.has_IA = True
            work_item.save()
        print(doc_details['file_path'])

    if len(created_IA_docs) == 0:
        bulk_message = 'All IA Docs have already been generated'
        work_items_list = WorkItem.objects.all()
        context = {
            'work_items_list': work_items_list,
            'bulk_message': bulk_message
        }
        return render(request, 'dashboard/index.html', context)

    path = os.path.join(os.getcwd(), 'docs\\IA')
    zip_name = os.path.join(path, 'IA_Documents.zip')
    with ZipFile(zip_name, 'w') as zip_object:
        for IA_doc in created_IA_docs:
            zip_object.write(IA_doc)

    if os.path.exists(zip_name):
        # !!Important read as binary!!
        with open(zip_name, 'rb') as zip_file:
            content = zip_file.read()
            response = HttpResponse(
                content,
                content_type='application/zip'
            )
            response['Content-Disposition'] = f'attachment; filename=IA_Documents.zip'
            response['Content-Length'] = len(content)
            return response
    else:
        bulk_message = "Couldn't download zip file"
        work_items_list = WorkItem.objects.all()
        context = {
            'work_items_list': work_items_list,
            'bulk_message': bulk_message
        }
        return render(request, 'dashboard/index.html', context)


def create_CR(request, pk):
    work_item = WorkItem.objects.get(id=pk)
    doc_details = create_excel(work_item)
    if doc_details['file_path'] is not None:
        work_item.has_CR = True
        work_item.save()

        filename = doc_details['file_name']
        filepath = doc_details['file_path']
        if os.path.exists(filepath):
            with open(filepath, 'rb') as worddoc: # !!Important read as binary!!
                content = worddoc.read()
                response = HttpResponse(
                    content,
                    content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
                )
                response['Content-Disposition'] = f'attachment; filename={filename}'
                response['Content-Length'] = len(content)
                return response
        else:
            work_item_comments = work_item.comment_set.all()
            context = {

dashboard/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Font Awesome CDN -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css"
        integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
    
        <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>{% block title %}{% endblock title %}</title>
</head>

<body>
    {% include "navbar.html" %}
    <div class="container">
        {% block content %}

        {% endblock content %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous">
    </script>

    
</body>

</html>

dashboard/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'dashboard:home' %}">Tracker</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dashboard:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dashboard:load_work_items' %}">Load Work Items</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dashboard:reset_IA' %}">Reset IA Fields</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dashboard:bulkcreate_IA' %}">Bulk Create IA Documents</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Download
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{% url 'dashboard:download_ia' %}">Download IA Documents</a>
            <a class="dropdown-item" href="{% url 'dashboard:download_cr' %}">Download CR Documents</a>
          </div>
        </li>
      </ul>
    </div>
</nav>